site_name: Spieleprogrammierung mit der Godot Engine

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  language: de
  #features:
    #- navigation.indexes  <-- Insiders only

markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

nav:
  - Startseite: index.md
  - Inhalt: contents.md
  - Installation: installation.md
  - Grundlagen:
    - Willkommen: basics/index.md
    - Aussprache: basics/pronounce.md
    - Ein Spiel starten: basics/start.md
    - Der Editor: basics/editor.md
    - Modden von Beispielen: basics/mods.md
    - Hello World: basics/hello.md
    - Ein Spiel entwickeln: basics/gamedev.md
    - Godot in der Übersicht: basics/godot.md
  - Dodge the Creeps!:
    - Spielidee: dodge-the-creeps/index.md
    - Projektorganisation: dodge-the-creeps/project.md
    - Spieler: dodge-the-creeps/player.md
    - Feinde: dodge-the-creeps/enemies.md
    - Szene: dodge-the-creeps/scene.md
    - HUD: dodge-the-creeps/hud.md
    - Erweiterungen: dodge-the-creeps/addons.md
  - Themengebiete:
    - Übersicht: topics/index.md
    - Export: topics/export.md
    - Asset Library: topics/assets.md
    - 2D Grafik: topics/2d.md
    - 3D Grafik: topics/3d.md
    - Sound: topics/sound.md
    - Physik: topics/physics.md
    - Animation: topics/animation.md
    - Input: topics/input.md 
    - Speichern/Laden: topics/io.md
    - GUI: topics/gui.md
    - VR: topics/vr.md
  - Clones:
    - Klone bekannter Spiele: clones/index.md
    - Pong: clones/pong/index.md
    - Flappy Bird: clones/flappy-bird/index.md
    - Doodle Jump: clones/doodle-jump/index.md
    - Angry Birds: clones/angry-birds/index.md
    - Super Mario: clones/super-mario/index.md
    - Among Us: clones/among-us/index.md
    - Minecraft: clones/minecraft/index.md



