site_name: Spieleprogrammierung mit der Godot Engine

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  language: de
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    #- navigation.indexes --> section pages (overviews)
    - navigation.instant # xhr hot reload
    - navigation.tracking # anchor tracking in url
    - navigation.top # back to top button
    - toc.follow # toc scrolls so the current point is visible
    #- toc.integrate --> toc of a page on the left
    - search.suggest

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/pwab/godot-clt-workshop
repo_name: pwab/godot-clt-workshop

nav:
  - Startseite: index.md
  - Einleitung:
    - Willkommen: introduction/welcome.md
    - Aussprache: introduction/pronounce.md
    - Fragen zu Godot: introduction/godot.md
  - Level 1:
    - Installation: level1/installation.md
    - Eine Demo starten: level1/start.md
    - Hello World: level1/hello.md
  - Level 2:
    - Spielfigur mit Bild: level2/player.md
    - Eingaben zur Bewegung: level2/input.md
    - Kollisionen: level2/collision.md
  - Level 3:
    - Eine Spielidee entwickeln: level3/gamedev.md
    - Den Editor kennenlernen: level3/editor.md
    - Modden von Beispielen: level3/mods.md
  - Level 4:
    - Dodge the creeps!: dodge-the-creeps/index.md
    - Let's Play: dodge-the-creeps/play.md
  - Wie geht es weiter?: next.md
  - Themengebiete:
    - Übersicht: topics/index.md
    - Export: topics/export.md
    - Asset Library: topics/assets.md
    - 2D Grafik: topics/2d.md
    - 3D Grafik: topics/3d.md
    - Sound: topics/sound.md
    - Physik: topics/physics.md
    - Animation: topics/animation.md
    - Input: topics/input.md 
    - Speichern/Laden: topics/io.md
    - GUI: topics/gui.md
    - KI: topics/ai.md
    - Multiplayer: topics/networking.md
    - VR: topics/vr.md
  - Clones:
    - Klone bekannter Spiele: clones/index.md
    - Pong: clones/pong/index.md
    - Flappy Bird: clones/flappy-bird/index.md
    - Doodle Jump: clones/doodle-jump/index.md
    - Angry Birds: clones/angry-birds/index.md
    - Super Mario: clones/super-mario/index.md
    - Among Us: clones/among-us/index.md
    - Minecraft: clones/minecraft/index.md
  - Hilfe: help.md
  - Glossar: glossary.md



