site_name: Spieleprogrammierung mit der Godot Engine

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  language: de
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    #- navigation.indexes --> section pages (overviews)
    - navigation.instant # xhr hot reload
    #- navigation.tracking # anchor tracking in url
    #- navigation.top # back to top button
    - toc.follow # toc scrolls so the current point is visible
    #- toc.integrate --> toc of a page on the left
    - search.suggest
    - content.code.copy # Code copy button
    - content.code.annotate # Code annotations

plugins:
  - search

markdown_extensions:
  - admonition
  - def_list
  - tables
  - abbr
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbrevations.md
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/pwab/godot-clt-workshop
repo_name: pwab/godot-clt-workshop

nav:
  - Startseite: index.md
  - Einleitung:
    - Willkommen: introduction/01_welcome-structure.md
    - Aussprache: introduction/02_pronounce.md
    - Fragen zu Godot: introduction/03_godot-faq.md
    - Installation: introduction/04_installation.md
    - Demo starten: introduction/05_start-demo.md
  - Level 1 > Hello Godot:
    - Erstes Projekt: level1/01_first-project.md
    - Erstes Node: level1/02_first-node.md
    - Erster Code: level1/03_first-code.md
    - Erste Einstellungen: level1/04_first-settings.md
    - Erste GUI: level1/05_first-gui.md
    - Erstes Bild: level1/06_first-image.md
    - Erste Animation: level1/07_first-animation.md
    - Erster Sound: level1/08_first-sound.md
    - Erste Eingaben: level1/09_first-input.md
  - Level 2 > Spielentwicklung:
    - Spielentwicklung: level2/gamedev.md
  - Level 3 > Minispiel Teil I:
    - Spielidee: level3/01_gameidea.md
    - Assets: level3/02_assets.md
    - Spielfigur: level3/03_character.md
    - Eingaben: level3/04_input.md
    - Karte: level3/05_map.md
    - Kollisionen: level3/06_collision.md
    - Gegner: level3/07_enemy.md
    - Spiellogik: level3/08_gamelogic.md
  - Level 4 > Godot Editor:
    - Der Godot Editor: level4/editor.md
  - Level 5 > Minispiel Teil II:
    - Menü: level5/01_gui-menu.md
    - Animationen: level5/02_animations.md
    - Soundeffekte: level5/03_soundeffects.md
    - Shader: level5/04_shader.md
    - Couch-Coop: level5/05_couch-coop.md
    - Speichern/Laden: level5/06_save-load.md
    - Gegner-KI: level5/07_enemy-ai.md
    - Export: level5/08_export.md
  - Extralevel:
    - Wie geht es weiter?: extralevel/next.md
    - Extralevel 1 > Dokumentation:
      - Lesen, lesen, lesen: extralevel/docs/index.md
      - Dodge the creeps: extralevel/docs/dodge-the-creeps.md
    - Extralevel 2 > Mods: extralevel/mods/index.md
    - Extralevel 3 > Klone:
      - Klone bekannter Spiele: extralevel/clones/index.md
      - Pong: extralevel/clones/pong/index.md
      - Flappy Bird: extralevel/clones/flappy-bird/index.md
      - Doodle Jump: extralevel/clones/doodle-jump/index.md
      - Angry Birds: extralevel/clones/angry-birds/index.md
      - Super Mario: extralevel/clones/super-mario/index.md
      - Among Us: extralevel/clones/among-us/index.md
      - Minecraft: extralevel/clones/minecraft/index.md
    - Extralevel 4 > Dein eigenes Spiel: extralevel/your-game/index.md
  - Themengebiete:
    - Übersicht: topics/index.md
    - Export: topics/export.md
    - Assets: topics/assets.md
    - 2D Grafik: topics/2d.md
    - 3D Grafik: topics/3d.md
    - Sound: topics/sound.md
    - Physik: topics/physics.md
    - Animation: topics/animation.md
    - Input: topics/input.md
    - Fehlerbehebung: topics/debugging.md
    - Speichern/Laden: topics/io.md
    - Export: topics/export.md
    - GUI: topics/gui.md
    - Shader: topics/shader.md
    - KI: topics/ai.md
    - Multiplayer: topics/networking.md
    - XR (VR/AR): topics/xr.md
  - Hilfe: help.md
  - Glossar: glossary.md



